# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            轻云志
tagline:          'Personal Blog'
description:      '落魄江湖载酒行'
url:              http://lament.xyz
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/LamentOfTheHighborne
